### ISSUE TITLE
Violates Terms of Use

### ISSUE THREAD

**Issue by Kyu** [sdushantha/fileinfo#2]
Hi, just a heads up, this repo violates the [TOS](https://fileinfo.com/terms) of FileInfo.com,
specifically:

> Usage Policy
You may use this website for the intended purpose of learning about file types and software programs. You may not use any kind of automatic device or program to access or copy any portion of FileInfo.com.  

You might wanna get permission from them if possible.

**Comment by sdushantha** [comment]
@Kyu  I am aware of this, but it confuses me a little. ```youtube-dl```, which is tool to download videos from many sites is very popular, isnt it violating the TOS of those sites? I am pretty sure that YouTube doesnt allow people to download videos from their site.

What I was thinking is that if ```youtube-dl``` can do that, then I can create this script.

Please do correct me if there is something wrong in what I said :)

**Comment by Kyu** [comment]
I mean I guess. Carry on
